version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - "6379:6379"
    volumes:
      - .data:/data

